Update APIURL
FAForever/UnitDB pull request #15
Opened 2023-02-04 21:05 UTC by MrRowey

- Update the APIURL to use the Internal content server rather than the API.
- All other changes are just code formatting due to my editor

2023-02-04 21:06 UTC, MrRowey commented
@Brutus5000 can we give this a try I'm assuming i have the correct endpoint for the content server

2023-02-12 21:42 UTC, Brutus5000 requested changes

2023-02-12 21:42 UTC, Brutus5000 commented on update.php
> +		$apiUrl = "https://content.faforever.com/featuredMods/0/files/%s";
That won't do it. This is the url to the API which gives you actual downloadable urls for these files.
You need to replace the urls in the result from `https://content.faforever.com` to `http://faf-content`

2023-02-14 20:05 UTC, Brutus5000 commented
You are still editing the wrong place. You need to query the api for the location of the right tiles. In the api response, there is a url to the content server that needs to be replaced. Maybe you just call the api and then you'll see what I mean

2023-05-12 20:53 UTC, closed without merging